# Generated by Django 3.2.15 on 2022-08-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sometable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name="person's first name")),
                ('last_name', models.CharField(max_length=30, verbose_name="person's first name")),
            ],
        ),
        migrations.DeleteModel(
            name='ArtsModel',
        ),
    ]
