# Generated by Django 3.2.15 on 2022-08-10 01:11

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0002_auto_20220810_0101'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sometable',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
