# Generated by Django 3.2.15 on 2022-08-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0003_alter_sometable_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SometableManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelManagers(
            name='sometable',
            managers=[
            ],
        ),
    ]
