# Generated by Django 3.2.15 on 2022-08-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0006_auto_20220810_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='artsadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usersname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
