# Generated by Django 3.2.15 on 2022-08-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0007_artsadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='artsproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artsname', models.CharField(max_length=128)),
                ('artsdescr', models.CharField(max_length=256)),
                ('artspath', models.CharField(max_length=300)),
                ('artsprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('artscatagory', models.CharField(max_length=15)),
            ],
        ),
    ]
