# Generated by Django 3.2.15 on 2022-08-11 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0009_artscategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artsproducts',
            name='artscatagory',
        ),
        migrations.RemoveField(
            model_name='artsproducts',
            name='artsdescr',
        ),
        migrations.RemoveField(
            model_name='artsproducts',
            name='artsname',
        ),
        migrations.RemoveField(
            model_name='artsproducts',
            name='artspath',
        ),
        migrations.RemoveField(
            model_name='artsproducts',
            name='artsprice',
        ),
        migrations.AddField(
            model_name='artsproducts',
            name='artsimage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
