# Generated by Django 3.2.15 on 2022-08-11 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0010_auto_20220811_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsproducts',
            name='artscatagory',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artsproducts',
            name='artsdescr',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artsproducts',
            name='artsname',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artsproducts',
            name='artspath',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artsproducts',
            name='artsprice',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=6),
            preserve_default=False,
        ),
    ]
