# Generated by Django 3.2.15 on 2022-08-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0012_alter_artsproducts_artscatagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsproducts',
            name='artsmis',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
