# Generated by Django 3.2.15 on 2022-08-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0013_artsproducts_artsmis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsproducts',
            name='artscatagory',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='artsproducts',
            name='artsdescr',
            field=models.CharField(default=' ', max_length=256),
        ),
        migrations.AlterField(
            model_name='artsproducts',
            name='artsimage',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='artsproducts',
            name='artsname',
            field=models.CharField(default=' ', max_length=128),
        ),
        migrations.AlterField(
            model_name='artsproducts',
            name='artspath',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='artsproducts',
            name='artsprice',
            field=models.DecimalField(decimal_places=2, default=' ', max_digits=6),
        ),
    ]
