# Generated by Django 3.2.15 on 2022-08-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0014_auto_20220811_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsproducts',
            name='artscatagory',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='artsproducts',
            name='artsmis',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='artsproducts',
            name='artsprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
