# Generated by Django 3.2.15 on 2022-08-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0015_auto_20220811_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsproducts',
            name='artsimage',
            field=models.ImageField(default=' ', max_length=500, upload_to='images/'),
        ),
    ]
