# Generated by Django 3.2.15 on 2022-08-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0016_alter_artsproducts_artsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsproducts',
            name='artsimage',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
    ]
