# Generated by Django 3.2.15 on 2022-08-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0017_alter_artsproducts_artsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsproducts',
            name='artsdescr',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
