# Generated by Django 3.2.15 on 2022-08-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0019_auto_20220811_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsproducts',
            name='artsimage',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='artsproducts',
            name='artscatagory',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='artsproducts',
            name='artsmis',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
