# Generated by Django 3.2.15 on 2022-08-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0021_alter_artsproducts_artsname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsproducts',
            name='artsimage',
            field=models.ImageField(default=' ', max_length=255, upload_to='images/'),
        ),
    ]
