# Generated by Django 3.2.15 on 2022-08-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0022_alter_artsproducts_artsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artsproducts',
            name='artscatagory',
        ),
        migrations.RemoveField(
            model_name='artsproducts',
            name='artsdescr',
        ),
        migrations.RemoveField(
            model_name='artsproducts',
            name='artsimage',
        ),
        migrations.RemoveField(
            model_name='artsproducts',
            name='artsname',
        ),
        migrations.RemoveField(
            model_name='artsproducts',
            name='artspath',
        ),
        migrations.RemoveField(
            model_name='artsproducts',
            name='artsprice',
        ),
    ]
