# Generated by Django 3.2.15 on 2022-08-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0023_auto_20220811_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsproducts',
            name='artscatagory',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='artsproducts',
            name='artsdescr',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='artsproducts',
            name='artsimage',
            field=models.ImageField(default=' ', max_length=255, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='artsproducts',
            name='artsname',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='artsproducts',
            name='artspath',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='artsproducts',
            name='artsprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
