# Generated by Django 3.2.15 on 2022-08-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0024_auto_20220811_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artsproducts',
            new_name='artbeatsproducts',
        ),
    ]
