# Generated by Django 3.2.15 on 2022-08-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0025_rename_artsproducts_artbeatsproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artbeatsproducts',
            name='artsimage',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
    ]
