# Generated by Django 3.2.15 on 2022-08-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0026_alter_artbeatsproducts_artsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artbeatsproducts',
            name='artsimage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
