# Generated by Django 3.2.15 on 2022-08-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0028_artsproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsproducts',
            name='products',
            field=models.CharField(max_length=50),
        ),
    ]
