# Generated by Django 3.2.15 on 2022-08-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0029_alter_artsproducts_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsproducts',
            name='products',
            field=models.TextField(default=' '),
        ),
    ]
