# Generated by Django 3.2.15 on 2022-08-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0030_alter_artsproducts_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='artbeatproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artsimage', models.ImageField(upload_to='images/')),
                ('artsname', models.TextField(default='')),
                ('artsdescr', models.TextField(default=' ')),
                ('artspath', models.TextField(default=' ')),
                ('artsprice', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('artscatagory', models.TextField(default=' ')),
                ('artsmis', models.TextField(default=' ')),
            ],
        ),
        
        migrations.AlterField(
            model_name='arts',
            name='descr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='arts',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
