# Generated by Django 3.2.15 on 2022-08-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0031_auto_20220811_2003'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='artbeatproducts',
            name='artsimage',
            field=models.ImageField(upload_to='template/milli/img'),
        ),
    ]
