# Generated by Django 3.2.15 on 2022-08-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milli', '0032_auto_20220811_2332'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='artbeatproducts',
            name='artsimage',
            field=models.ImageField(upload_to='static/milli/img'),
        ),
    ]
